{% set version = "1.0" %}

{% set posix = 'm2-' if win else '' %}

package:
  name: r-mqtl
  version: {{ version|replace("-", "_") }}

source:
  fn: mQTL_{{ version }}.tar.gz
  url:
    - https://cran.r-project.org/src/contrib/mQTL_{{ version }}.tar.gz
    - https://cran.r-project.org/src/contrib/Archive/mQTL/mQTL_{{ version }}.tar.gz
  sha256: 21193861fbf2d280f2b7284ba87d68adce515e35fbe4e71821439fa8b14d1b72

build:
  number: 1007
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}    # [not win]
    - {{ stdlib("c") }}      # [not win]
    - {{ compiler('m2w64_c') }}  # [win]
    - {{ stdlib("m2w64_c") }}    # [win]
  host:
    - r-base
    - r-mass
    - r-outliers
    - r-qtl
  run:
    - r-base
    - r-mass
    - r-outliers
    - r-qtl

test:
  commands:
    - $R -e "library('mQTL')"  # [not win]
    - "\"%R%\" -e \"library('mQTL')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=mQTL
  license: GPL
  summary: mQTL provides a complete QTL analysis pipeline for metabolomic data.  Distinctive features include normalisation using PQN approach, peak alignment   using RSPA approach, dimensionality reduction using SRV approach and finally  QTL mapping using R/qtl package.
  license_family: GPL
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3
extra:
  recipe-maintainers:
    - conda-forge/r
    - MathiasHaudgaard
    - FrodePedersen
    - ArneKr
