travis:
  secure:
    BINSTAR_TOKEN: zZw0RReWOMhedN+m4CeCL5y9xREixJP0y9EclTGixTI0IgXkXp850G3S9sD9YakqhkvxH+tVlyNAHORmZtW5Ass6IiDP0rkkvHHRFbii+KMjEGtJpJH0IKKDhb4WtR8yFEze679BmNTYpC5gvscQjVO4Z/sFZxTlIAxnE/uNFJqlEvCLAkPRCNWP7erVIlLdQ62KsHsWmQhyqSkfv+E2s9l9e8GNxnbt5UjNcGwXL4nu2a14azbWMFG2LqtL5+PXto36LdU3205RAWOMKWO4zNQVBOoofo1I1cq8eOVzzcu1byaA4CaSxT03e7u1SjxDBwhUAKLomf4AJ++b+dFZUtunlCZp/I0Vts/bC8i1JOTaIXGYdJik6IxUBoUBbaxMLkB6bMn5604O6r4997B26GS8/38gLK8QUXXf8PYl9/L41W/YblZgS27c9+d5RqvaU8jx+sfrK2LzIIioGm7vAM8iR0r49550/Qr1AHARrrxUrwfwg2N/XcII1XrRKI8Kf9OIgvt7y+Lu+u23qMNfyhEJXR/miCXSQUmlmWsvhHIlEhJ4WjVM8iFFjxno965+xeERdCrvBqblnxLKGwDV+gcPKa2H+0LJMi9IqUbMc+CxXKd6AbtUbe6IUga0yyTqrGhsCYUkxGJ2PzUDw/mYJUtHrL9PGiCmT+12Z2RW8rg=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
