travis:
  secure:
    BINSTAR_TOKEN: fpnQjwJLsg/pYsRrnGOD3Z0zpTkpg4WHdHQuTJz4r1owPmVZjvvr7OOqYDEbtv+bxPFz580r/HRvFlVwZZo1ztN9rWoiRav/4uLoGXW7l+ne8qhYwkhbVwz/NDBNpLObZRj7o3PxmMUrWbI2AvO70Iuk9bbNYeLPdocua5gjDW6yenGR4ZJOyQalyjkcBfyr74Rp2e0Amu7EmmtmDy6VCHdZbdb2TLKA235NsjxtxNqAOpJ7JVpTJV+JEUMF78rsCodNGT7ovKgbz8CXklIWKaLCwEAQl2mUKEgpypLYqRNZqfE4HZVjM/oKXJyvJBLOPBMS1WiSvcbQyaJaLfJBBseamLanZnneh7t8Gbi0JUuV37/jsDxW+6TtMyMgkzjhL18YflfcFVcr8SAEnObOwb2WUGPHkTA1kRZrAKdZ7DSpEFRAt5ljDG/M8hqDD9jA2bzZFruAG8XO7sXNQAIAF5peCZmQ5jMCB+aVgGVWqi/9GhOtJ5j4vHbBDdJlTd/TjGC09za4Be+kU40awkrzp3ZPLa6ZFOJLx8U0YcbwbFEf9HSzKh1gLKd0mIh6dwwSgcGx477AaBDQCiq5F94XckwQPhViJ59FBLKNnbDqWs4QesGcI35AoTb0USZVpaQ2nA1TcurKqtDS9szaQTeRK+fo/dHpu/ugsiZPUbC23V4=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
